### ISSUE TITLE
Redirect appends query string on CiviCRM 5.26+

### ISSUE THREAD

**Issue by kcristiano** [mecachisenros/cfc-redirect#3]
With the changes to CiviCRM for the upcoming WP change to redirect_canonical the redirect appends the quesry string.

Example:

https://cvdemo.tadpole.cc/civicrm/event/register/?reset=1&id=11  redirects to https://cvdemo.tadpole.cc/annual-conference/?event_id=11&civiwp=CiviCRM  

It should redirect to https://cvdemo.tadpole.cc/annual-conference

**Comment by mecachisenros** [comment]
@kcristiano should be fixed on latest master.
